// Copyright 2026 opslog Author. All Rights Reserved.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//      http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.0
// source: pkg/transport/grpctx/ingest/ingest.proto

package ingest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_pkg_transport_grpctx_ingest_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_grpctx_ingest_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_pkg_transport_grpctx_ingest_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendReply) Reset() {
	*x = SendReply{}
	mi := &file_pkg_transport_grpctx_ingest_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReply) ProtoMessage() {}

func (x *SendReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_transport_grpctx_ingest_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReply.ProtoReflect.Descriptor instead.
func (*SendReply) Descriptor() ([]byte, []int) {
	return file_pkg_transport_grpctx_ingest_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *SendReply) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

var File_pkg_transport_grpctx_ingest_ingest_proto protoreflect.FileDescriptor

const file_pkg_transport_grpctx_ingest_ingest_proto_rawDesc = "" +
	"\n" +
	"(pkg/transport/grpctx/ingest/ingest.proto\x12\ropslog.ingest\"'\n" +
	"\vSendRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"'\n" +
	"\tSendReply\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted2\x8c\x01\n" +
	"\x06Ingest\x12<\n" +
	"\x04Send\x12\x1a.opslog.ingest.SendRequest\x1a\x18.opslog.ingest.SendReply\x12D\n" +
	"\n" +
	"SendStream\x12\x1a.opslog.ingest.SendRequest\x1a\x18.opslog.ingest.SendReply(\x01BAZ?github.com/go-the-way/opslog/pkg/transport/grpctx/ingest;ingestb\x06proto3"

var (
	file_pkg_transport_grpctx_ingest_ingest_proto_rawDescOnce sync.Once
	file_pkg_transport_grpctx_ingest_ingest_proto_rawDescData []byte
)

func file_pkg_transport_grpctx_ingest_ingest_proto_rawDescGZIP() []byte {
	file_pkg_transport_grpctx_ingest_ingest_proto_rawDescOnce.Do(func() {
		file_pkg_transport_grpctx_ingest_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_transport_grpctx_ingest_ingest_proto_rawDesc), len(file_pkg_transport_grpctx_ingest_ingest_proto_rawDesc)))
	})
	return file_pkg_transport_grpctx_ingest_ingest_proto_rawDescData
}

var file_pkg_transport_grpctx_ingest_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_transport_grpctx_ingest_ingest_proto_goTypes = []any{
	(*SendRequest)(nil), // 0: opslog.ingest.SendRequest
	(*SendReply)(nil),   // 1: opslog.ingest.SendReply
}
var file_pkg_transport_grpctx_ingest_ingest_proto_depIdxs = []int32{
	0, // 0: opslog.ingest.Ingest.Send:input_type -> opslog.ingest.SendRequest
	0, // 1: opslog.ingest.Ingest.SendStream:input_type -> opslog.ingest.SendRequest
	1, // 2: opslog.ingest.Ingest.Send:output_type -> opslog.ingest.SendReply
	1, // 3: opslog.ingest.Ingest.SendStream:output_type -> opslog.ingest.SendReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_transport_grpctx_ingest_ingest_proto_init() }
func file_pkg_transport_grpctx_ingest_ingest_proto_init() {
	if File_pkg_transport_grpctx_ingest_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_transport_grpctx_ingest_ingest_proto_rawDesc), len(file_pkg_transport_grpctx_ingest_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_transport_grpctx_ingest_ingest_proto_goTypes,
		DependencyIndexes: file_pkg_transport_grpctx_ingest_ingest_proto_depIdxs,
		MessageInfos:      file_pkg_transport_grpctx_ingest_ingest_proto_msgTypes,
	}.Build()
	File_pkg_transport_grpctx_ingest_ingest_proto = out.File
	file_pkg_transport_grpctx_ingest_ingest_proto_goTypes = nil
	file_pkg_transport_grpctx_ingest_ingest_proto_depIdxs = nil
}
